### Create employee
POST localhost:8080/api/v1/employee/create
Content-Type: application/json

{
  "firstName": "Suhrob",
  "lastName": "Qarshiyev",
  "phoneNumber": "900986269",
  "departmentName": "IT",
  "position": "Dasturchi"
}

### Update employee
PUT localhost:8080/api/v1/employee/b76e9e0a-9ff2-4c72-8907-1c8e29f933a7
Content-Type: application/json

{
  "firstName": "Suhrab",
  "lastName": "Qarshiyev",
  "phoneNumber": "+998900986269",
  "departmentName": "ROBOTEX",
  "position": "Menejer"
}

### Get by id
GET localhost:8080/api/v1/employee/0a8c532c-9c88-4966-a136-23fd121a5f9f

### Get all with pagination
GET localhost:8080/api/v1/employee/all?page=1&size=2

### Filter with pagination
GET localhost:8080/api/v1/employee/search?page=1&size=1
Content-Type: application/json

{
  "query": "suh"
}