### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Apply leave
POST localhost:8080/api/v1/leaves/apply
Content-Type: application/json

{
  "employeeId": "9ac326a5-6518-4292-adc3-aec9b8ed0485",
  "reason": "Asal",
  "leaveType": "SPECIAL",
  "startDate": "2025-11-25",
  "endDate": "2025-11-30"
}

### Get all
GET localhost:8080/api/v1/leaves/all

### Get by id
GET localhost:8080/api/v1/leaves/5095e193-6496-444d-8faa-c0331741cd98

### Approve leave
PUT localhost:8080/api/v1/leaves/5095e193-6496-444d-8faa-c0331741cd98/approve

### Reject leave
PUT localhost:8080/api/v1/leaves/db2125fd-ead0-4d91-b58c-3e936379d82a/reject

### Delete applicatoin
DELETE localhost:8080/api/v1/leaves/6ed1f9a6-5ed2-4e98-aea2-dd00105b8e25